/*
 * Savora — fast food, snacks, eggs, drinks, ice creams, cakes, sweets, soups & salads.
 * Copyright (c) 2026 Abhiram Upadrashta — MIT License
 */
(function (root) {
  'use strict';
  var A = root.__AK, add = A.add, S = A.S, I = A.I;
  function each(list, fn) { list.forEach(fn); }

  // ------------------------------------------------------------------ starters & snacks: fillings × styles
  var FILL = { Paneer: ['veg', '250 g paneer cubes', '#f7ecd0'], Chicken: ['nonveg', '400 g boneless chicken', '#c9803f'], Gobi: ['veg', '1 cauliflower, florets', '#efe3c0'], Mushroom: ['veg', '250 g mushrooms', '#b99a78'], 'Baby Corn': ['veg', '200 g baby corn', '#f0d36a'], Fish: ['nonveg', '400 g boneless fish', '#e0a15a'], Prawn: ['nonveg', '300 g prawns', '#f08a5d'], Egg: ['egg', '6 boiled eggs, halved', '#fff2c8'], Soya: ['vegan', '1½ cups soya chunks, boiled', '#a8754a'], Potato: ['vegan', '3 potatoes, wedges', '#e8c36a'], Tofu: ['vegan', '250 g tofu cubes', '#f3ead6'] };
  var STARTER = [
    ['65', 'south', 'Spicy · Crunchy', 'Marinate with ginger-garlic, chilli, curd, cornflour and rice flour; deep-fry, then toss with curry leaves and green chillies.', 'fry', 'Paneer Chicken Gobi Mushroom Baby~Corn Fish Prawn Egg Soya'],
    ['Manchurian', 'chinese', 'Tangy · Garlicky', 'Coat in cornflour batter and fry; toss in a garlic-ginger soy sauce with spring onions.', 'fry', 'Paneer Chicken Gobi Mushroom Baby~Corn Soya Tofu'],
    ['Chilli', 'chinese', 'Hot · Tangy', 'Fry batter-coated pieces; toss with capsicum, onion petals, green chillies, soy and chilli sauce.', 'fry', 'Paneer Chicken Gobi Mushroom Baby~Corn Fish Prawn Egg Soya Potato Tofu'],
    ['Tikka', 'north', 'Smoky · Charred', 'Marinate in hung curd, tandoori masala, mustard oil and lemon; skewer and grill until charred.', 'grill', 'Paneer Chicken Mushroom Fish Prawn Soya Gobi Tofu'],
    ['Pakora', 'north', 'Crispy · Spiced', 'Dip in a spiced besan batter with ajwain and deep-fry until golden.', 'fry', 'Paneer Chicken Gobi Mushroom Fish Egg Potato'],
    ['Pepper Fry', 'south', 'Peppery · Dry', 'Toss with crushed pepper, curry leaves, fennel and caramelised onions.', 'fry', 'Baby~Corn Soya Tofu Potato'],
    ['Popcorn', 'fast', 'Crunchy · Snacky', 'Coat in seasoned flour, dip in batter, roll in cornflakes and fry into bite-size pops.', 'fry', 'Paneer Chicken Prawn Mushroom'],
    ['Lollipop', 'chinese', 'Spicy · Juicy', 'Shape into lollipops, coat in red chilli batter and deep-fry; serve with schezwan dip.', 'fry', 'Chicken'],
    ['Hariyali Tikka', 'north', 'Herby · Smoky', 'Marinate in mint-coriander-spinach paste with curd; grill until spotted.', 'grill', 'Paneer Chicken Mushroom Fish'],
    ['Malai Tikka', 'north', 'Creamy · Mild', 'Marinate in cream, cheese, cashew paste and cardamom; grill gently.', 'grill', 'Paneer Chicken Mushroom Soya'],
    ['Seekh Kebab', 'north', 'Smoky · Juicy', 'Mince with onion, herbs and spices, shape around skewers and grill.', 'grill', 'Chicken Soya Paneer'],
    ['Crispy Fried', 'fast', 'Crispy · Golden', 'Double-dredge in spiced flour and buttermilk; fry until extra crunchy.', 'fry', 'Chicken Fish Prawn Baby~Corn Mushroom'],
    ['Salt & Pepper', 'chinese', 'Peppery · Light', 'Fry lightly battered pieces and toss with salt, pepper, garlic and spring onion.', 'fry', 'Tofu Mushroom Prawn Chicken Potato Baby~Corn']
  ];
  each(STARTER, function (s) {
    s[5].split(' ').forEach(function (fk) {
      fk = fk.replace('~', ' ');
      var f = FILL[fk];
      var diet = f[0], dairy = /curd|cream|cheese|buttermilk/.test(s[3]);
      if (diet === 'vegan' && dairy) diet = 'veg';
      var nm = s[0] === '65' ? fk + ' 65' : s[0] === 'Seekh Kebab' ? fk + ' Seekh Kebab' : /Tikka|Pakora|Popcorn|Lollipop|Pepper Fry/.test(s[0]) ? fk + ' ' + s[0] : s[0] + ' ' + fk;
      if (fk === 'Egg' && s[0] === 'Pakora') nm = 'Egg Bonda';
      add({ name: nm, diet: diet, region: s[1] === 'fast' ? 'fast' : s[1], cats: ['snacks', 'starter', s[1] === 'chinese' ? 'chinese' : s[1], s[1] === 'fast' || s[1] === 'chinese' ? 'fast' : '', fk === 'Paneer' ? 'paneer' : '', fk === 'Egg' ? 'eggs' : ''],
        kcal: (diet === 'nonveg' ? 330 : 280) + (s[4] === 'fry' ? 60 : 0), flav: s[2], serves: 3,
        ing: [I('', f[1]), I('1 tbsp', 'ginger-garlic paste'), I('1 tsp', 'chilli powder'), I('3 tbsp', 'cornflour'), I('2 tbsp', s[4] === 'grill' ? 'hung curd' : 'maida'), I('1 tsp', 'lemon juice'), I('', s[4] === 'fry' ? 'oil for frying' : '2 tbsp mustard oil'), I('', 'salt')],
        steps: [S('chop', 'Cut the ' + fk.toLowerCase() + ' into bite-size pieces and pat dry.', 5), S('marinate', 'Marinate with ginger-garlic paste, chilli powder, lemon juice and salt for 15 minutes.', 15), S(s[4], s[3], 12), S('garnish', 'Garnish with onion rings, lemon wedges and coriander. Serve hot with green chutney.', 1)],
        art: { kind: s[4] === 'grill' ? 'kebab' : 'fry', base: /Chilli|Manchurian|Lollipop/.test(s[0]) ? '#b8331f' : s[0] === '65' ? '#c93b22' : /Hariyali/.test(s[0]) ? '#5f8f3a' : /Malai/.test(s[0]) ? '#eed9a8' : '#c98a3f', pc: f[2] } });
    });
  });
  // chaats & street food
  var STREET = [['Pav Bhaji', 'veg', 'Buttery · Spicy', [I('4', 'potatoes, boiled'), I('1 cup', 'mixed veg (peas, cauliflower, capsicum)'), I('3', 'tomatoes'), I('2 tbsp', 'pav bhaji masala'), I('4 tbsp', 'butter'), I('8', 'pav buns')], 'Mash the boiled vegetables with tomato, onion, butter and pav bhaji masala; toast pav in butter.', 'curry', '#c9452a', 420],
    ['Vada Pav', 'veg', 'Spicy · Filling', [I('4', 'potatoes, boiled & mashed'), I('1 cup', 'besan batter'), I('4', 'pav'), I('', 'green & garlic chutneys')], 'Make spiced potato balls, dip in besan batter and fry; sandwich in pav with chutneys.', 'burger', '#e0a13a', 300],
    ['Dabeli', 'veg', 'Sweet · Spicy', [I('4', 'pav'), I('3', 'potatoes, boiled'), I('2 tbsp', 'dabeli masala'), I('¼ cup', 'masala peanuts'), I('¼ cup', 'pomegranate')], 'Cook potatoes with dabeli masala and tamarind chutney; stuff in pav with peanuts and pomegranate.', 'burger', '#c96a3a', 290],
    ['Pani Puri', 'vegan', 'Tangy · Refreshing', [I('30', 'puris'), I('1 cup', 'boiled potato & chana'), I('4 cups', 'mint-tamarind pani'), I('', 'sweet chutney')], 'Crack each puri, fill with potato-chana, dip in spicy pani and eat in one bite.', 'chaat', '#7fb04a', 250],
    ['Bhel Puri', 'vegan', 'Tangy · Crunchy', [I('3 cups', 'puffed rice'), I('½ cup', 'sev'), I('1', 'onion'), I('1', 'tomato'), I('', 'tamarind & mint chutneys')], 'Toss puffed rice with onion, tomato, chutneys and sev just before serving.', 'chaat', '#e5b84d', 220],
    ['Sev Puri', 'veg', 'Tangy · Crunchy', [I('16', 'papdis'), I('1', 'potato, boiled'), I('', 'chutneys'), I('½ cup', 'sev')], 'Top papdis with potato, onion, chutneys and a mound of sev.', 'chaat', '#e3a445', 240],
    ['Dahi Puri', 'veg', 'Sweet · Tangy', [I('20', 'puris'), I('1 cup', 'sweet curd'), I('', 'chutneys & sev')], 'Fill puris with potato, pour sweet curd and chutneys, top with sev.', 'chaat', '#f1e2c0', 260],
    ['Samosa', 'vegan', 'Crispy · Spiced', [I('2 cups', 'maida'), I('4 tbsp', 'oil (for dough)'), I('3', 'potatoes, boiled'), I('½ cup', 'peas'), I('1 tsp', 'garam masala')], 'Stuff cones of dough with spiced potato-peas, seal and fry slowly until blistered and golden.', 'samosa', '#d9a04a', 260],
    ['Aloo Tikki Chaat', 'veg', 'Tangy · Crispy', [I('4', 'potatoes, boiled'), I('2 tbsp', 'cornflour'), I('1 cup', 'curd'), I('', 'chutneys')], 'Shallow-fry potato patties; top with curd, chutneys and chaat masala.', 'chaat', '#d99a45', 300],
    ['Kachori', 'vegan', 'Flaky · Spicy', [I('2 cups', 'maida'), I('1 cup', 'moong dal filling')], 'Fill dough with spiced moong dal, flatten and fry slowly until puffed and flaky.', 'samosa', '#d6a052', 280],
    ['Onion Bhaji', 'vegan', 'Crispy · Spiced', [I('3', 'onions, sliced'), I('1 cup', 'besan'), I('2', 'green chillies'), I('½ tsp', 'ajwain')], 'Massage onions with salt, mix with besan and spices, drop clusters into hot oil.', 'fry', '#d99a3f', 230],
    ['Mirchi Bajji', 'vegan', 'Hot · Crispy', [I('8', 'large green chillies'), I('1 cup', 'besan'), I('½ tsp', 'ajwain')], 'Slit and deseed the chillies, stuff with tamarind masala, dip in batter and fry.', 'fry', '#7ba33a', 210],
    ['Punugulu', 'veg', 'Crispy · Soft', [I('2 cups', 'dosa batter'), I('1', 'onion'), I('2 tbsp', 'rice flour')], 'Mix onion and rice flour into dosa batter and drop small balls into hot oil.', 'vada', '#e0b25a', 230],
    ['Bread Pakora', 'veg', 'Crispy · Filling', [I('4', 'bread slices'), I('1 cup', 'potato stuffing'), I('1 cup', 'besan batter')], 'Sandwich spiced potato between bread, dip in batter and fry.', 'fry', '#d8953c', 290],
    ['Dhokla', 'veg', 'Spongy · Sweet-sour', [I('1 cup', 'besan'), I('½ cup', 'curd'), I('1 tsp', 'Eno'), I('', 'mustard-curry leaf tempering')], 'Whisk besan with curd, add Eno and steam 15 minutes; pour sweet tempering on top.', 'idli', '#f2cf4a', 180],
    ['Khandvi', 'veg', 'Silky · Mild', [I('1 cup', 'besan'), I('1 cup', 'buttermilk'), I('', 'tempering & coconut')], 'Cook besan with buttermilk to a thick paste, spread thin, roll up and temper.', 'idli', '#f1d060', 170],
    ['Kathi Roll (Paneer)', 'veg', 'Spicy · Wrap', [I('2', 'parathas'), I('200 g', 'paneer tikka'), I('1', 'onion'), I('', 'mint mayo')], 'Wrap paneer tikka with onions and mint mayo in a flaky paratha.', 'roll', '#d9a25a', 380],
    ['Kathi Roll (Chicken)', 'nonveg', 'Spicy · Wrap', [I('2', 'parathas'), I('250 g', 'chicken tikka'), I('2', 'eggs'), I('', 'onion & green chutney')], 'Cook an egg on the paratha, flip, add chicken tikka and onions, and roll.', 'roll', '#c9803f', 450],
    ['Egg Roll', 'egg', 'Savoury · Wrap', [I('2', 'parathas'), I('3', 'eggs'), I('1', 'onion'), I('', 'ketchup & chilli sauce')], 'Pour beaten egg on a hot tawa, place a paratha on top, flip, fill with onions and sauces and roll.', 'roll', '#e9c77a', 360],
    ['Chicken Shawarma', 'nonveg', 'Garlicky · Juicy', [I('400 g', 'chicken thighs, sliced'), I('4', 'pita / kuboos'), I('½ cup', 'toum (garlic sauce)'), I('', 'pickles, lettuce, fries')], 'Marinate chicken in shawarma spices, pan-roast until charred, wrap with garlic sauce and pickles.', 'roll', '#d49a55', 520],
    ['Veg Momos', 'vegan', 'Juicy · Mild', [I('2 cups', 'maida'), I('2 cups', 'cabbage, carrot, onion, finely chopped'), I('1 tbsp', 'ginger-garlic'), I('1 tbsp', 'soy sauce')], 'Fill thin dough circles with the veggie filling, pleat and steam 12 minutes.', 'momos', '#f4ecd8', 230],
    ['Chicken Momos', 'nonveg', 'Juicy · Savoury', [I('2 cups', 'maida'), I('300 g', 'chicken mince'), I('1', 'onion'), I('1 tbsp', 'ginger-garlic')], 'Fill dough circles with seasoned chicken mince, pleat and steam 15 minutes.', 'momos', '#f3ead3', 300],
    ['Paneer Momos', 'veg', 'Soft · Mild', [I('2 cups', 'maida'), I('200 g', 'paneer, crumbled'), I('1', 'onion'), I('1 tsp', 'pepper')], 'Fill with seasoned crumbled paneer, pleat and steam 12 minutes.', 'momos', '#f6efdc', 280],
    ['Fried Momos', 'veg', 'Crispy · Juicy', [I('12', 'steamed veg momos'), I('', 'oil for frying')], 'Deep-fry the steamed momos until golden and crisp.', 'momos', '#e2b56a', 320],
    ['Tandoori Momos', 'veg', 'Smoky · Spicy', [I('12', 'steamed momos'), I('½ cup', 'tandoori marinade')], 'Coat steamed momos in tandoori marinade and grill until charred.', 'momos', '#d0602e', 310],
    ['Spring Rolls', 'vegan', 'Crispy · Light', [I('10', 'spring roll sheets'), I('2 cups', 'stir-fried cabbage, carrot & noodles')], 'Roll the stir-fry in sheets, seal and deep-fry until crisp.', 'roll', '#e3b25e', 260],
    ['Cheese Balls', 'veg', 'Gooey · Crispy', [I('1 cup', 'grated cheese'), I('2', 'potatoes, boiled'), I('½ cup', 'breadcrumbs')], 'Mix cheese and potato, shape balls, crumb-coat and fry.', 'fry', '#e8b44a', 340],
    ['Hara Bhara Kabab', 'vegan', 'Herby · Crispy', [I('2 cups', 'spinach & peas'), I('2', 'potatoes'), I('2 tbsp', 'besan')], 'Blend blanched spinach and peas with potato and spices; shape and shallow-fry.', 'kebab', '#5d9a3c', 220],
    ['Corn Cheese Balls', 'veg', 'Cheesy · Sweet corn', [I('1 cup', 'sweet corn'), I('1 cup', 'cheese'), I('2', 'potatoes')], 'Mix corn, cheese and potato, crumb and fry.', 'fry', '#f0c54a', 330],
    ['Masala Peanuts', 'vegan', 'Crunchy · Spicy', [I('1 cup', 'peanuts'), I('½ cup', 'besan'), I('1 tsp', 'chilli powder')], 'Coat peanuts in spiced besan with a sprinkle of water and fry until crunchy.', 'bowl', '#b9784a', 300]
  ];
  each(STREET, function (s) {
    add({ name: s[0], diet: s[1], region: 'fast', cats: ['fast', 'snacks', 'street', /Paneer/.test(s[0]) ? 'paneer' : '', s[1] === 'egg' ? 'eggs' : ''], kcal: s[7], flav: s[2], serves: 3,
      ing: s[3].concat([I('', 'salt & spices to taste')]), steps: [S('chop', 'Prep everything: chop the onions, tomatoes and herbs, and keep the chutneys ready.', 6), S(s[5] === 'momos' ? 'knead' : s[5] === 'samosa' ? 'knead' : 'mix', s[4].split(';')[0] + '.', 8), S(s[5] === 'momos' || s[5] === 'idli' ? 'steam' : s[5] === 'curry' ? 'saute' : s[5] === 'chaat' ? 'mix' : 'fry', (s[4].split(';')[1] || s[4].split(',').slice(-1)[0]).trim(), 10), S('serve', 'Serve right away — street food is best hot and fresh!', 1)],
      art: { kind: s[5], base: s[6] } });
  });

  // ------------------------------------------------------------------ burgers, pizzas, sandwiches, pasta, fries
  each([['Veg Burger', 'veg', 'veg patty'], ['Aloo Tikki Burger', 'veg', 'spiced potato tikki'], ['Paneer Burger', 'veg', 'crispy paneer slab'], ['Chicken Burger', 'nonveg', 'grilled chicken patty'], ['Crispy Chicken Burger', 'nonveg', 'fried chicken fillet'], ['Egg Burger', 'egg', 'fried egg & omelette'], ['Fish Burger', 'nonveg', 'crumbed fish fillet'], ['Mushroom Swiss Burger', 'veg', 'sautéed mushrooms & cheese'], ['Double Cheese Burger', 'veg', 'two veg patties & double cheese'], ['BBQ Chicken Burger', 'nonveg', 'BBQ-glazed chicken'], ['Vegan Bean Burger', 'vegan', 'black bean patty'], ['Spicy Masala Burger', 'veg', 'masala potato-peas patty']], function (b) {
    add({ name: b[0], diet: b[1], region: 'fast', cats: ['fast', 'burger', /Paneer/.test(b[0]) ? 'paneer' : '', b[1] === 'egg' ? 'eggs' : ''], kcal: b[1] === 'nonveg' ? 560 : 480, flav: /Spicy|BBQ/.test(b[0]) ? 'Spicy · Smoky' : 'Cheesy · Juicy', serves: 2,
      ing: [I('2', 'burger buns'), I('2', b[2]), I('2', b[1] === 'vegan' ? 'lettuce leaves (no cheese)' : 'cheese slices'), I('1', 'tomato, sliced'), I('1', 'onion, rings'), I('2 tbsp', b[1] === 'vegan' ? 'vegan mayo' : 'mayonnaise'), I('1 tbsp', 'ketchup'), I('1 tbsp', 'butter')],
      steps: [S('chop', 'Slice tomato and onion; wash the lettuce.', 3), S('fry', 'Cook the ' + b[2] + ' on a hot pan until golden on both sides.', 8), S('grill', 'Butter and toast the buns cut-side down.', 2), S('add', 'Layer: sauce, lettuce, patty, cheese, tomato, onion.', 2), S('serve', 'Close, press gently and serve with fries.', 1)],
      art: { kind: 'burger', base: '#d99a3f', pc: b[1] === 'nonveg' ? '#8a4a25' : '#c98a3a' } });
  });
  each([['Margherita', 'veg', 'fresh tomato sauce, mozzarella & basil'], ['Veg Supreme', 'veg', 'capsicum, onion, olives, corn & mushroom'], ['Farmhouse', 'veg', 'onion, capsicum, tomato & mushroom'], ['Paneer Tikka', 'veg', 'tandoori paneer & onion'], ['Chicken Tikka', 'nonveg', 'chicken tikka & capsicum'], ['BBQ Chicken', 'nonveg', 'BBQ chicken & red onion'], ['Corn & Cheese', 'veg', 'sweet corn & extra cheese'], ['Mushroom', 'veg', 'garlic mushrooms'], ['Peri Peri Chicken', 'nonveg', 'peri peri chicken & jalapeño'], ['Tandoori Paneer', 'veg', 'tandoori paneer & mint mayo'], ['Veggie Vegan', 'vegan', 'veggies & cashew cheese'], ['Egg & Cheese', 'egg', 'sliced boiled egg & cheese'], ['Pepper Barbecue', 'nonveg', 'barbecue chicken & capsicum'], ['Four Cheese', 'veg', 'mozzarella, cheddar, parmesan & paneer']], function (p) {
    add({ name: p[0] + ' Pizza', diet: p[1], region: 'fast', cats: ['fast', 'pizza', /Paneer/.test(p[0]) ? 'paneer' : '', p[1] === 'egg' ? 'eggs' : ''], kcal: p[1] === 'nonveg' ? 320 : 290, flav: /Peri|Tikka|Tandoori/.test(p[0]) ? 'Spicy · Cheesy' : 'Cheesy · Herby', serves: 2,
      ing: [I('1', '10-inch pizza base (or dough: 2 cups maida, 1 tsp yeast, 1 tsp sugar)'), I('4 tbsp', 'pizza sauce'), I('1½ cups', p[1] === 'vegan' ? 'cashew cheese' : 'mozzarella, grated'), I('', 'toppings: ' + p[2]), I('1 tsp', 'oregano'), I('1 tsp', 'chilli flakes'), I('1 tbsp', 'olive oil')],
      steps: [S('knead', 'If making dough: knead maida, yeast, sugar, salt and warm water; rise 1 hour.', 10), S('roll', 'Stretch the dough into a thin round and prick with a fork.', 3), S('add', 'Spread sauce, scatter cheese and the toppings: ' + p[2] + '.', 3), S('bake', 'Bake at 220°C for 12–15 minutes until the crust is golden and cheese bubbles.', 14), S('serve', 'Sprinkle oregano and chilli flakes, slice and serve.', 1)],
      art: { kind: 'pizza', base: '#e8a23c' } });
  });
  each([['Veg Grilled Sandwich', 'veg'], ['Cheese Chilli Toast', 'veg'], ['Bombay Masala Sandwich', 'veg'], ['Club Sandwich', 'nonveg'], ['Chicken Mayo Sandwich', 'nonveg'], ['Egg Mayo Sandwich', 'egg'], ['Paneer Tikka Sandwich', 'veg'], ['Corn Cheese Sandwich', 'veg'], ['Veg Coleslaw Sandwich', 'veg'], ['Peanut Butter Banana Toast', 'vegan'], ['Avocado Toast', 'vegan'], ['Egg Bhurji Sandwich', 'egg'], ['Chutney Sandwich', 'vegan'], ['Aloo Masala Toast', 'vegan'], ['Garlic Bread', 'veg'], ['Cheese Garlic Bread', 'veg']], function (s) {
    var nm = s[0];
    add({ name: nm, diet: s[1], region: 'fast', cats: ['fast', 'sandwich', 'breakfast', /Paneer/.test(nm) ? 'paneer' : '', s[1] === 'egg' ? 'eggs' : ''], kcal: s[1] === 'nonveg' ? 420 : 330, flav: /Chilli|Masala|Tikka/.test(nm) ? 'Spicy · Toasty' : 'Toasty · Comforting', serves: 2,
      ing: [I('4', 'bread slices'), I('', /Garlic/.test(nm) ? '3 tbsp garlic butter' : 'filling for ' + nm.replace(/ (Sandwich|Toast)$/, '').toLowerCase()), I('2 tbsp', s[1] === 'vegan' ? 'olive oil' : 'butter'), I('2 tbsp', 'green chutney or mayo'), I('', 'salt & pepper')],
      steps: [S('chop', 'Prepare the filling — slice, mash or mix the ingredients.', 5), S('add', 'Spread butter and chutney on the bread and layer the filling.', 3), S('grill', 'Toast in a sandwich maker or on a tawa until golden and crisp.', 5), S('serve', 'Cut diagonally and serve hot with ketchup.', 1)],
      art: { kind: 'sandwich', base: '#e2b263' } });
  });
  each([['White Sauce Pasta', 'veg', 'creamy béchamel'], ['Red Sauce Pasta', 'vegan', 'tangy tomato-basil'], ['Pink Sauce Pasta', 'veg', 'tomato cream'], ['Pesto Pasta', 'veg', 'basil pesto'], ['Aglio e Olio', 'vegan', 'garlic, olive oil & chilli'], ['Mac and Cheese', 'veg', 'cheddar cheese sauce'], ['Chicken Alfredo Pasta', 'nonveg', 'parmesan cream & chicken'], ['Arrabbiata Pasta', 'vegan', 'spicy tomato'], ['Masala Pasta', 'vegan', 'Indian masala'], ['Chicken Spaghetti Bolognese', 'nonveg', 'chicken mince tomato ragù'], ['Paneer Tikka Pasta', 'veg', 'tikka masala cream']], function (p) {
    add({ name: p[0], diet: p[1], region: 'fast', cats: ['fast', 'pasta', 'world', /Paneer/.test(p[0]) ? 'paneer' : ''], kcal: p[1] === 'vegan' ? 380 : 470, flav: /Arrabbiata|Masala|Aglio/.test(p[0]) ? 'Spicy · Garlicky' : 'Creamy · Cheesy', serves: 2,
      ing: [I('200 g', /Spaghetti|Aglio/.test(p[0]) ? 'spaghetti' : /Mac/.test(p[0]) ? 'macaroni' : 'penne'), I('', 'sauce: ' + p[2]), I('1 tbsp', 'garlic, minced'), I('1 cup', 'capsicum, corn & broccoli'), I('2 tbsp', 'olive oil'), I('1 tsp', 'oregano & chilli flakes')],
      steps: [S('boil', 'Boil the pasta in plenty of salted water until al dente; save ½ cup pasta water.', 10), S('saute', 'Sauté garlic in olive oil, add the vegetables and cook 3 minutes.', 4), S('simmer', 'Add the ' + p[2] + ' sauce and simmer 3 minutes.', 3), S('stir', 'Toss in the pasta with a splash of pasta water until glossy.', 2), S('garnish', 'Finish with oregano, chilli flakes' + (p[1] === 'vegan' ? '' : ' and parmesan') + '.', 1)],
      art: { kind: 'pasta', base: /White|Alfredo|Mac/.test(p[0]) ? '#f1e3b8' : /Pesto/.test(p[0]) ? '#6f9e3a' : /Pink/.test(p[0]) ? '#e79a7a' : '#d2502b' } });
  });
  each([['French Fries', 'vegan', 'salt'], ['Peri Peri Fries', 'vegan', 'peri peri seasoning'], ['Masala Fries', 'vegan', 'chaat masala & chilli'], ['Cheesy Loaded Fries', 'veg', 'cheese sauce & jalapeños'], ['Potato Wedges', 'vegan', 'herbs & garlic'], ['Sweet Potato Fries', 'vegan', 'paprika'], ['Chicken Nuggets', 'nonveg', 'crumbed chicken'], ['Fried Chicken', 'nonveg', 'crispy buttermilk chicken'], ['BBQ Chicken Wings', 'nonveg', 'BBQ glaze'], ['Buffalo Wings', 'nonveg', 'hot buffalo sauce'], ['Hot Dog', 'nonveg', 'chicken sausage'], ['Nachos with Salsa', 'vegan', 'tomato salsa'], ['Cheese Nachos', 'veg', 'cheese sauce'], ['Veg Quesadilla', 'veg', 'cheese & peppers'], ['Chicken Tacos', 'nonveg', 'spiced chicken & salsa'], ['Veg Tacos', 'vegan', 'beans & salsa'], ['Onion Rings', 'veg', 'crispy batter']], function (f) {
    var fries = /Fries|Wedges/.test(f[0]);
    add({ name: f[0], diet: f[1], region: 'fast', cats: ['fast', 'snacks', 'world'], kcal: f[1] === 'nonveg' ? 450 : 360, flav: /Peri|Masala|Buffalo|Hot/.test(f[0]) ? 'Spicy · Crispy' : 'Crispy · Salty', serves: 2,
      ing: [I('', fries ? '3 large potatoes, cut into sticks' : 'main: ' + f[2]), I('', 'seasoning: ' + f[2]), I('2 tbsp', 'cornflour'), I('', 'oil for frying'), I('', 'salt')],
      steps: fries ? [S('chop', 'Cut potatoes into even sticks and soak in cold water 20 minutes; pat dry.', 20), S('fry', 'Fry once at low heat 5 minutes, rest, then fry again on high until golden and crisp.', 10), S('stir', 'Toss with ' + f[2] + ' while hot.', 1), S('serve', 'Serve with ketchup and mayo.', 1)]
        : [S('chop', 'Prep the ' + f[2] + ' and pat dry.', 5), S('marinate', 'Season well and coat.', 10), S(/Tacos|Quesadilla|Nachos/.test(f[0]) ? 'grill' : 'fry', 'Cook until crisp and golden.', 10), S('serve', 'Serve hot with dips.', 1)],
      art: { kind: fries ? 'fries' : /Tacos|Nachos|Quesadilla/.test(f[0]) ? 'taco' : 'fry', base: '#e9b54a' } });
  });
  // Maggi / instant noodles (bachelor favourites)
  each([['Masala Maggi', 'veg', 'the classic masala'], ['Cheese Maggi', 'veg', 'cheese slice'], ['Egg Maggi', 'egg', 'scrambled egg'], ['Vegetable Maggi', 'vegan', 'peas, carrot & onion'], ['Schezwan Maggi', 'vegan', 'schezwan sauce'], ['Butter Garlic Maggi', 'veg', 'butter & garlic'], ['Chicken Maggi', 'nonveg', 'leftover chicken'], ['Soupy Maggi', 'vegan', 'extra water & pepper'], ['Paneer Maggi', 'veg', 'paneer cubes'], ['Tadka Maggi', 'vegan', 'mustard & curry leaf tadka']], function (m) {
    add({ name: m[0], diet: m[1], region: 'fast', cats: ['fast', 'noodles', 'bachelor', /Paneer/.test(m[0]) ? 'paneer' : '', m[1] === 'egg' ? 'eggs' : ''], kcal: 350, flav: 'Comforting · Quick', serves: 1, time: 10,
      ing: [I('1 pack', 'instant noodles with tastemaker'), I('1½ cups', 'water'), I('', m[2]), I('1', 'onion, chopped'), I('1', 'green chilli')],
      steps: [S('saute', 'Sauté onion and chilli (and ' + m[2] + ') in a little oil for 2 minutes.', 2), S('boil', 'Add water and the tastemaker; bring to a boil.', 2), S('add', 'Break in the noodles and cook 2 minutes, stirring.', 2), S('serve', 'Serve steaming hot — bachelor comfort food!', 1)],
      art: { kind: 'noodles', base: '#e8b74a' } });
  });

  // ------------------------------------------------------------------ egg specials
  each([['Masala Omelette', 'Spicy · Fluffy', 'omelette'], ['Cheese Omelette', 'Cheesy · Fluffy', 'omelette'], ['Veggie Omelette', 'Fresh · Fluffy', 'omelette'], ['Mushroom Omelette', 'Earthy · Fluffy', 'omelette'], ['Spanish Omelette', 'Hearty · Potato', 'omelette'], ['Bread Omelette', 'Street style · Filling', 'omelette'], ['Egg Bhurji', 'Spicy · Scrambled', 'bhurji'], ['Scrambled Eggs', 'Creamy · Buttery', 'bhurji'], ['French Toast', 'Sweet · Eggy', 'toast'], ['Masala French Toast', 'Spicy · Eggy', 'toast'], ['Boiled Egg Fry', 'Spicy · Crisp', 'fry'], ['Egg Roast (Kerala)', 'Spicy · Onion-rich', 'curry'], ['Egg Keema', 'Spicy · Minced', 'bhurji'], ['Shakshuka', 'Tangy · Tomato', 'curry'], ['Poached Eggs on Toast', 'Light · Classic', 'toast'], ['Sunny Side Up', 'Simple · Runny', 'fry'], ['Egg Pepper Fry', 'Peppery · Dry', 'fry'], ['Deviled Eggs', 'Creamy · Tangy', 'fry'], ['Egg Salad', 'Creamy · Fresh', 'salad'], ['Egg Puff', 'Flaky · Savoury', 'samosa'], ['Egg Paniyaram', 'Soft · Savoury', 'idli'], ['Egg Chilli Fry', 'Spicy · Indo-Chinese', 'fry'], ['Egg Mughlai', 'Rich · Creamy', 'curry'], ['Egg Ghotala', 'Spicy · Mumbai street', 'bhurji'], ['Egg Kothu Parotta', 'Spicy · Chopped', 'bhurji'], ['Egg Fried Maggi', 'Quick · Savoury', 'noodles'], ['Egg Noodles Soup', 'Warming · Light', 'soup'], ['Egg Drop Soup', 'Light · Silky', 'soup'], ['Egg Sandwich', 'Classic · Filling', 'sandwich'], ['Egg Pulusu', 'Tangy · Andhra', 'curry'], ['Egg Bread Upma', 'Quick · Savoury', 'bhurji'], ['Egg Dosa Roll', 'Crisp · Savoury', 'dosa']], function (e) {
    add({ name: e[0], diet: 'egg', region: /Kerala|Kothu|Pulusu|Paniyaram|Dosa/.test(e[0]) ? 'south' : /Ghotala|Keema|Mughlai|Bhurji|Masala/.test(e[0]) ? 'north' : 'fast', cats: ['eggs', 'breakfast', /Kerala|Kothu|Pulusu|Paniyaram|Dosa/.test(e[0]) ? 'south' : /Ghotala|Keema|Mughlai|Bhurji/.test(e[0]) ? 'north' : ''], kcal: /Toast|Puff|Kothu/.test(e[0]) ? 340 : 240, flav: e[1], serves: 2,
      ing: [I('4', 'eggs'), I('1', 'onion, finely chopped'), I('1', 'tomato, chopped'), I('2', 'green chillies'), I('¼ tsp', 'turmeric'), I('½ tsp', 'pepper'), I('2 tbsp', 'butter or oil'), I('2 tbsp', 'coriander'), I('', 'salt')].concat(/Toast|Sandwich|Bread/.test(e[0]) ? [I('4', 'bread slices')] : /Cheese/.test(e[0]) ? [I('¼ cup', 'grated cheese')] : /Mushroom/.test(e[0]) ? [I('1 cup', 'mushrooms')] : []),
      steps: e[2] === 'omelette' ? [S('chop', 'Chop onion, tomato, chillies and coriander finely.', 3), S('whisk', 'Whisk the eggs with salt, pepper and turmeric until frothy; fold in the veggies.', 2), S('pour', 'Pour into a hot buttered pan and swirl.', 1), S('fry', 'Cook on medium until the base sets, flip and cook 1 more minute.', 3), S('serve', 'Fold and serve hot.', 1)]
        : e[2] === 'bhurji' ? [S('chop', 'Chop onion, tomato and chillies.', 3), S('saute', 'Sauté onion, chillies and tomato in butter until soft.', 5), S('add', 'Crack in the eggs with turmeric, pepper and salt.', 1), S('stir', 'Scramble on low heat until just set and soft.', 3), S('garnish', 'Finish with coriander; serve with pav or toast.', 1)]
        : e[2] === 'toast' ? [S('whisk', 'Whisk eggs with a splash of milk, salt/sugar and spices.', 2), S('add', 'Dip the bread slices in the egg mixture.', 1), S('fry', 'Toast on a buttered pan until golden on both sides.', 5), S('serve', 'Serve warm.', 1)]
        : e[2] === 'curry' ? [S('boil', 'Hard-boil the eggs, peel and make slits.', 12), S('saute', 'Cook onions until golden, then tomatoes and spices into a thick masala.', 12), S('add', 'Add the eggs and simmer 5 minutes.', 5), S('serve', 'Serve with appam, rice or chapati.', 1)]
        : [S('boil', 'Hard-boil the eggs, peel and halve (or use as the recipe needs).', 12), S('fry', 'Fry with onion, chilli, pepper and curry leaves until coated and crisp.', 6), S('serve', 'Serve hot as a side or snack.', 1)],
      art: { kind: e[2] === 'omelette' ? 'omelette' : e[2] === 'curry' ? 'curry' : e[2] === 'toast' || e[2] === 'sandwich' ? 'sandwich' : e[2] === 'soup' ? 'soup' : e[2] === 'noodles' ? 'noodles' : 'egg', base: e[2] === 'curry' ? '#b8502a' : '#f3d36a', piece: 'egg', pc: '#fff2c8' } });
  });

  // ------------------------------------------------------------------ non-veg specials
  each([['Tandoori Chicken', 'north', 'grill'], ['Chicken Tangdi Kebab', 'north', 'grill'], ['Chicken Sukka', 'south', 'fry'], ['Mutton Sukka', 'south', 'fry'], ['Mutton Keema', 'north', 'saute'], ['Keema Pav', 'north', 'saute'], ['Andhra Chicken Fry', 'south', 'fry'], ['Chicken Chinthamani', 'south', 'fry'], ['Apollo Fish', 'south', 'fry'], ['Amritsari Fish Fry', 'north', 'fry'], ['Kerala Fish Fry', 'south', 'fry'], ['Tawa Fish Fry', 'south', 'fry'], ['Fish Moilee', 'south', 'simmer'], ['Bengali Fish Curry (Macher Jhol)', 'north', 'simmer'], ['Goan Fish Curry', 'south', 'simmer'], ['Andhra Chepala Pulusu', 'south', 'simmer'], ['Prawn Masala', 'south', 'saute'], ['Prawn Fry', 'south', 'fry'], ['Crab Masala', 'south', 'saute'], ['Mutton Paya', 'north', 'pressure'], ['Haleem', 'south', 'pressure'], ['Nihari', 'north', 'simmer'], ['Chicken Kathi Kebab', 'north', 'grill'], ['Grilled Chicken', 'fast', 'grill'], ['Chicken Stew', 'south', 'simmer'], ['Chilli Garlic Prawns', 'chinese', 'fry'], ['Kozhi Varuval', 'south', 'fry'], ['Mutton Chukka', 'south', 'fry'], ['Chicken Afghani', 'north', 'grill'], ['Chicken Reshmi Kebab', 'north', 'grill'], ['Chicken Changezi', 'north', 'simmer'], ['Mutton Kosha', 'north', 'saute'], ['Chicken Cafreal', 'south', 'fry'], ['Pork-free Chicken Chorizo Rice', 'fast', 'saute'], ['Fish Tikka', 'north', 'grill'], ['Squid Fry', 'south', 'fry']], function (n) {
    var meat = /Mutton|Keema|Paya|Haleem|Nihari/.test(n[0]) ? 'mutton' : /Fish|Macher|Chepala/.test(n[0]) ? 'fish' : /Prawn/.test(n[0]) ? 'prawns' : /Crab/.test(n[0]) ? 'crab' : /Squid/.test(n[0]) ? 'squid rings' : 'chicken';
    add({ name: n[0], diet: 'nonveg', region: n[1], cats: [n[1], n[1] === 'chinese' ? 'fast' : '', 'nvspecial'], kcal: meat === 'mutton' ? 420 : 330, flav: n[2] === 'grill' ? 'Smoky · Juicy' : n[2] === 'simmer' ? 'Rich · Aromatic' : 'Spicy · Bold', serves: 4, level: 'Chef level',
      ing: [I(meat === 'crab' ? '4' : '500 g', meat), I('1½ tbsp', 'ginger-garlic paste'), I('2 tsp', 'chilli powder'), I('1 tsp', 'garam masala'), I('½ tsp', 'turmeric'), I('2', 'onions'), I('2 tbsp', 'lemon juice or tamarind'), I('3 tbsp', 'oil or ghee'), I('1 sprig', 'curry leaves / coriander')],
      steps: [S('chop', 'Clean the ' + meat + ' well and cut into pieces.', 8), S('marinate', 'Marinate with ginger-garlic paste, chilli, turmeric, lemon and salt for 30 minutes.', 30), meat === 'mutton' ? S('pressure', 'Pressure-cook until tender.', 30) : null,
        S(n[2] === 'pressure' ? 'pressure' : n[2], n[2] === 'grill' ? 'Grill over high heat, basting with butter, until charred and cooked through.' : n[2] === 'simmer' ? 'Cook in a spiced onion-tomato (or coconut) gravy until tender and aromatic.' : n[2] === 'fry' ? 'Fry in hot oil with onions and curry leaves, roasting until dark and dry.' : 'Cook with onions and spices on high, stirring until the masala coats everything.', 15),
        S('garnish', 'Finish with garam masala, lemon and fresh herbs. Serve hot.', 1)],
      art: { kind: n[2] === 'grill' ? 'kebab' : n[2] === 'simmer' ? 'curry' : 'fry', base: n[2] === 'simmer' ? '#c8612c' : '#a83a1e', piece: meat === 'fish' ? 'fillet' : meat === 'prawns' ? 'prawn' : 'chunk', pc: '#b56a33' } });
  });

  // ------------------------------------------------------------------ soups & salads
  each([['Tomato Soup', 'vegan', '#d6452a'], ['Sweet Corn Veg Soup', 'vegan', '#f2d56a'], ['Sweet Corn Chicken Soup', 'nonveg', '#efd27a'], ['Hot and Sour Veg Soup', 'vegan', '#8a4a2a'], ['Hot and Sour Chicken Soup', 'nonveg', '#8a4a2a'], ['Manchow Soup', 'vegan', '#6a3a22'], ['Lemon Coriander Soup', 'vegan', '#d9d98a'], ['Cream of Mushroom Soup', 'veg', '#cdb79a'], ['Broccoli Almond Soup', 'veg', '#8db35a'], ['Pumpkin Soup', 'vegan', '#e98a2f'], ['Mulligatawny Soup', 'vegan', '#d6923a'], ['Chicken Clear Soup', 'nonveg', '#e8d9a6'], ['Mutton Paya Soup', 'nonveg', '#caa36a'], ['Palak Soup', 'veg', '#4f8a35'], ['Carrot Ginger Soup', 'vegan', '#ee8a2f'], ['Minestrone', 'vegan', '#c85a32'], ['Chicken Noodle Soup', 'nonveg', '#e3cf8a'], ['Dal Shorba', 'vegan', '#e0b24a']], function (s) {
    add({ name: s[0], diet: s[1], region: 'world', cats: ['soups'], kcal: 130, flav: /Hot|Manchow/.test(s[0]) ? 'Hot · Tangy' : /Cream|Almond/.test(s[0]) ? 'Creamy · Smooth' : 'Light · Comforting', serves: 3,
      ing: [I('2 cups', 'main: ' + s[0].replace(/ Soup$/, '').toLowerCase()), I('1', 'onion'), I('3 cloves', 'garlic'), I('3 cups', s[1] === 'nonveg' ? 'chicken stock' : 'vegetable stock'), I('1 tbsp', s[1] === 'veg' ? 'butter' : 'oil'), I('1 tbsp', 'cornflour slurry'), I('', 'salt & pepper')],
      steps: [S('chop', 'Chop the vegetables' + (s[1] === 'nonveg' ? ' and shred the meat' : '') + ' finely.', 6), S('saute', 'Sauté onion and garlic 3 minutes.', 3), S('boil', 'Add the main ingredients and stock; simmer 12 minutes.', 12), /Tomato|Pumpkin|Mushroom|Broccoli|Carrot|Palak/.test(s[0]) ? S('blend', 'Blend until smooth and return to the pot.', 3) : S('stir', 'Stir in the cornflour slurry to thicken slightly.', 2), S('garnish', 'Season, garnish and serve steaming hot.', 1)],
      art: { kind: 'soup', base: s[2] } });
  });
  each([['Kachumber Salad', 'vegan', '#d9533a'], ['Sprouts Salad', 'vegan', '#9cc25a'], ['Chickpea Salad', 'vegan', '#d6a652'], ['Greek Salad', 'veg', '#79b04a'], ['Chicken Caesar Salad', 'nonveg', '#9fc56a'], ['Fruit Salad', 'vegan', '#f08a4a'], ['Pasta Salad', 'veg', '#e8c06a'], ['Russian Salad', 'veg', '#f1e6b8'], ['Quinoa Salad', 'vegan', '#c9b77a'], ['Paneer Tikka Salad', 'veg', '#e89a4a'], ['Corn Salad', 'vegan', '#f2d04a'], ['Beetroot Salad', 'vegan', '#a3264a'], ['Watermelon Feta Salad', 'veg', '#ef5a6a'], ['Egg & Potato Salad', 'egg', '#f3e08a']], function (s) {
    add({ name: s[0], diet: s[1], region: 'world', cats: ['soups', 'salad', /Paneer/.test(s[0]) ? 'paneer' : '', s[1] === 'egg' ? 'eggs' : ''], kcal: 170, flav: 'Fresh · Crunchy', serves: 2,
      ing: [I('2 cups', 'main: ' + s[0].replace(/ Salad$/, '').toLowerCase()), I('1', 'cucumber'), I('1', 'onion'), I('1 tbsp', 'lemon juice'), I('1 tbsp', 'olive oil'), I('½ tsp', 'chaat masala'), I('2 tbsp', 'coriander or mint')],
      steps: [S('chop', 'Chop everything into even bite-size pieces.', 6), S('mix', 'Whisk lemon juice, olive oil, salt and chaat masala into a dressing.', 1), S('stir', 'Toss the salad with the dressing just before serving.', 1), S('garnish', 'Top with herbs and serve chilled.', 1)],
      art: { kind: 'salad', base: s[2] } });
  });

  // ------------------------------------------------------------------ DRINKS
  var SHAKE = [['Chocolate', '#6b3a22'], ['Strawberry', '#f28aa6'], ['Mango', '#f7b733'], ['Banana', '#f3dc8a'], ['Vanilla', '#f6ecd0'], ['Oreo', '#7a6a62'], ['KitKat', '#8a5a3a'], ['Butterscotch', '#e0a64a'], ['Chikoo', '#b98a5a'], ['Dates', '#8a5234'], ['Dry Fruit', '#d9b27a'], ['Rose', '#f29ab4'], ['Badam', '#f1dca0'], ['Coffee', '#8a5a3a'], ['Pista', '#b9d48a'], ['Blueberry', '#6a5aa8'], ['Caramel', '#c98a3a'], ['Peanut Butter', '#c99a5a'], ['Avocado', '#a8c86a'], ['Sitaphal', '#f1eadc'], ['Papaya', '#f59a4a'], ['Black Currant', '#5a2a5a'], ['Apple', '#e8e0b0'], ['Nutella', '#6b3a22'], ['Brownie', '#5a3322'], ['Kesar', '#f3c75a']];
  each(SHAKE, function (s) {
    add({ name: s[0] + ' Milkshake', diet: 'veg', region: 'drinks', cats: ['drinks', 'shakes'], kcal: 280, flav: 'Sweet · Creamy', serves: 2, time: 8,
      ing: [I('2 cups', 'chilled milk'), I('', s[0].toLowerCase() + (/Mango|Banana|Strawberry|Chikoo|Avocado|Papaya|Apple|Sitaphal|Blueberry/.test(s[0]) ? ' — 1 cup chopped' : ' — flavouring as needed')), I('2 scoops', 'vanilla ice cream'), I('2 tbsp', 'sugar'), I('6', 'ice cubes')],
      steps: [S('chop', 'Prepare the ' + s[0].toLowerCase() + ' (chop fruit or measure the flavouring).', 3), S('blend', 'Blend with chilled milk, sugar, ice and one scoop of ice cream until frothy.', 2), S('pour', 'Pour into tall glasses.', 1), S('garnish', 'Top with the second scoop, a drizzle and a straw. Serve immediately.', 1)],
      art: { kind: 'shake', base: s[1] } });
    if (/Mango|Banana|Chocolate|Strawberry|Dates|Peanut/.test(s[0])) add({ name: 'Vegan ' + s[0] + ' Shake', diet: 'vegan', region: 'drinks', cats: ['drinks', 'shakes'], kcal: 220, flav: 'Sweet · Creamy', serves: 2, time: 8,
      ing: [I('2 cups', 'chilled oat or almond milk'), I('', s[0].toLowerCase()), I('2', 'dates (to sweeten)'), I('6', 'ice cubes')], steps: [S('blend', 'Blend everything until smooth and frothy.', 2), S('pour', 'Pour into glasses.', 1), S('serve', 'Serve chilled.', 1)], art: { kind: 'shake', base: s[1] } });
  });
  var LASSI = [['Sweet Lassi', '#f6ecd6', 'sugar & cardamom'], ['Salted Lassi', '#f2eee0', 'salt & roasted cumin'], ['Mango Lassi', '#f7b733', 'mango pulp'], ['Rose Lassi', '#f29ab4', 'rose syrup'], ['Strawberry Lassi', '#f28aa6', 'strawberries'], ['Banana Lassi', '#f3dc8a', 'ripe banana'], ['Dry Fruit Lassi', '#e2c48a', 'chopped dry fruits'], ['Masala Chaas', '#e9ecd8', 'ginger, green chilli, mint & cumin'], ['Mint Chaas', '#cfe6b8', 'mint'], ['Jeera Chaas', '#ecead4', 'roasted cumin'], ['Kesar Lassi', '#f3cf73', 'saffron'], ['Punjabi Malai Lassi', '#f6efe0', 'thick malai']];
  each(LASSI, function (l) {
    add({ name: l[0], diet: 'veg', region: 'drinks', cats: ['drinks', 'lassi', /Chaas/.test(l[0]) ? '' : 'north'], kcal: /Chaas|Salted/.test(l[0]) ? 80 : 220, flav: /Chaas|Salted/.test(l[0]) ? 'Cool · Savoury' : 'Sweet · Creamy', serves: 2, time: 7,
      ing: [I('2 cups', 'thick curd'), I('', l[2]), I('½ cup', 'chilled water or milk'), I('6', 'ice cubes')],
      steps: [S('whisk', 'Whisk the curd until smooth.', 2), S('blend', 'Blend with ' + l[2] + ' and chilled water/milk until frothy.', 2), S('pour', 'Pour into chilled glasses.', 1), S('garnish', 'Garnish and serve cold.', 1)], art: { kind: 'lassi', base: l[1] } });
  });
  var MOCK = [['Virgin Mojito', '#c9ecb0', 'lime & mint'], ['Blue Lagoon', '#3aa6e8', 'blue curaçao syrup & lemon'], ['Watermelon Mojito', '#f06a7a', 'watermelon & mint'], ['Strawberry Mojito', '#f06a8a', 'strawberry & mint'], ['Kiwi Cooler', '#8ac24a', 'kiwi & lime'], ['Green Apple Fizz', '#a8d86a', 'green apple syrup'], ['Passion Fruit Cooler', '#f3a82f', 'passion fruit'], ['Virgin Piña Colada', '#f6e6b0', 'pineapple & coconut cream'], ['Shirley Temple', '#f25a6a', 'grenadine & ginger ale'], ['Sunrise Mocktail', '#f79a3a', 'orange juice & grenadine'], ['Lemon Mint Cooler', '#d8ef9a', 'lemon & mint'], ['Ginger Lemon Fizz', '#efe6a0', 'ginger & lemon'], ['Cucumber Cooler', '#c8e8b0', 'cucumber & mint'], ['Litchi Cooler', '#f6e2e0', 'litchi'], ['Pineapple Mint Cooler', '#f3d45a', 'pineapple & mint'], ['Orange Mint Fizz', '#f59a2a', 'orange & mint'], ['Blueberry Lemonade', '#7a6ad0', 'blueberry & lemon'], ['Rose Lemonade', '#f5a6c0', 'rose & lemon'], ['Guava Chilli Cooler', '#f28a8a', 'guava & chilli'], ['Mango Mojito', '#f7b733', 'mango & mint']];
  each(MOCK, function (m) {
    add({ name: m[0], diet: 'vegan', region: 'drinks', cats: ['drinks', 'mocktail'], kcal: 120, flav: 'Fizzy · Refreshing', serves: 2, time: 6,
      ing: [I('', m[2]), I('2 tbsp', 'sugar syrup'), I('1 cup', 'crushed ice'), I('2 cups', 'chilled soda / sprite'), I('', 'lime wedges & mint for garnish')],
      steps: [S('mix', 'Muddle ' + m[2] + ' with sugar syrup in the glass.', 2), S('add', 'Fill with crushed ice.', 1), S('pour', 'Top up with chilled soda and stir gently.', 1), S('garnish', 'Garnish with a lime wheel and mint sprig. Serve fizzy!', 1)], art: { kind: 'mocktail', base: m[1] } });
  });
  var JUICE = [['Nimbu Pani', '#eef2b0', 'lemon, sugar & black salt'], ['Masala Soda', '#e6e9c0', 'lemon, soda & chaat masala'], ['Jaljeera', '#9cb04a', 'cumin, mint & tamarind'], ['Aam Panna', '#d9e27a', 'raw mango'], ['Kokum Sharbat', '#8a1f4a', 'kokum'], ['Rose Sharbat', '#f28aa6', 'rose syrup'], ['Sugarcane Juice', '#c8d88a', 'sugarcane & ginger'], ['Watermelon Juice', '#f25a6a', 'watermelon'], ['Orange Juice', '#f7a02a', 'oranges'], ['Pineapple Juice', '#f3d44a', 'pineapple'], ['Pomegranate Juice', '#b3203a', 'pomegranate'], ['Mosambi Juice', '#f2e27a', 'sweet lime'], ['ABC Juice', '#b8303a', 'apple, beetroot & carrot'], ['Carrot Juice', '#f28a2a', 'carrot & ginger'], ['Grape Juice', '#6a2a6a', 'black grapes'], ['Guava Juice', '#f29a9a', 'guava'], ['Muskmelon Juice', '#f6c27a', 'muskmelon'], ['Tender Coconut Cooler', '#f4f6ea', 'tender coconut water & malai'], ['Bael Sharbat', '#e0a64a', 'wood apple'], ['Sattu Drink', '#d9c49a', 'sattu, lemon & cumin'], ['Panakam', '#c9953f', 'jaggery, ginger & cardamom'], ['Nannari Sarbath', '#b3202a', 'nannari syrup & lemon'], ['Solkadhi', '#c56a8a', 'kokum & coconut milk'], ['Amla Juice', '#b8d86a', 'amla & honey-free ginger'], ['Beetroot Cooler', '#a3264a', 'beetroot & lemon'], ['Apple Juice', '#efd79a', 'apples'], ['Mint Lemonade', '#cfeea0', 'lemon & mint'], ['Ginger Ale (Homemade)', '#efd99a', 'ginger syrup & soda'], ['Homemade Cola', '#4a2a1a', 'spiced caramel syrup & soda'], ['Iced Hibiscus Tea', '#b3203a', 'hibiscus petals']];
  each(JUICE, function (j) {
    add({ name: j[0], diet: 'vegan', region: 'drinks', cats: ['drinks', 'juice'], kcal: 110, flav: /Jaljeera|Masala|Aam|Sattu/.test(j[0]) ? 'Tangy · Cooling' : 'Fresh · Sweet', serves: 2, time: 8,
      ing: [I('', j[2]), I('2 tbsp', 'sugar or jaggery (adjust)'), I('2 cups', 'chilled water or soda'), I('', 'ice cubes'), I('pinch', 'black salt')],
      steps: [S('chop', 'Prepare the ' + j[2] + ' — peel, chop or squeeze.', 4), S('blend', 'Blend or mix with sugar and chilled water; strain if needed.', 2), S('pour', 'Pour over ice.', 1), S('garnish', 'Garnish with mint or lemon. Serve chilled.', 1)], art: { kind: 'juice', base: j[1] } });
  });
  var COLD = [['Cold Coffee', '#b98a5a', 'veg'], ['Dalgona Coffee', '#c98a4a', 'veg'], ['Iced Latte', '#c9a47a', 'veg'], ['Mocha Frappe', '#7a4a2a', 'veg'], ['Caramel Frappe', '#c98a3a', 'veg'], ['Hazelnut Frappe', '#a8784a', 'veg'], ['Cold Brew', '#3a2418', 'vegan'], ['Lemon Iced Tea', '#d98a2a', 'vegan'], ['Peach Iced Tea', '#f2a05a', 'vegan'], ['Masala Iced Tea', '#b8702a', 'vegan'], ['Thandai', '#f1dca0', 'veg'], ['Rose Falooda', '#f28aa6', 'veg'], ['Badam Milk', '#f3dc9a', 'veg'], ['Rose Milk', '#f5b0c6', 'veg'], ['Jigarthanda', '#c9a07a', 'veg'], ['Kesar Milk', '#f3cf73', 'veg'], ['Cold Chocolate', '#5a3322', 'veg'], ['Matcha Latte (Iced)', '#8fbf5a', 'veg'], ['Banana Oats Smoothie', '#e8d49a', 'vegan'], ['Berry Blast Smoothie', '#a8305a', 'vegan'], ['Mango Smoothie', '#f7b733', 'vegan'], ['Green Detox Smoothie', '#7fb04a', 'vegan'], ['Peanut Butter Smoothie', '#c99a5a', 'vegan'], ['Tropical Smoothie', '#f3a83a', 'vegan'], ['Chia Seed Smoothie', '#d9c6e8', 'vegan'], ['Papaya Smoothie', '#f59a4a', 'vegan'], ['Dates Smoothie', '#8a5234', 'vegan'], ['Spinach Apple Smoothie', '#8ac25a', 'vegan']];
  each(COLD, function (c) {
    var smoothie = /Smoothie/.test(c[0]);
    add({ name: c[0], diet: c[2], region: 'drinks', cats: ['drinks', smoothie ? 'smoothie' : /Coffee|Latte|Frappe|Brew|Mocha|Tea/.test(c[0]) ? 'coffee' : 'milk'], kcal: smoothie ? 190 : c[2] === 'vegan' ? 60 : 230, flav: /Coffee|Brew|Frappe|Mocha/.test(c[0]) ? 'Bold · Chilled' : 'Sweet · Chilled', serves: 2, time: 8,
      ing: [I('', 'base: ' + c[0].toLowerCase().replace(/ \(.*\)/, '')), I('2 cups', c[2] === 'vegan' ? (smoothie ? 'almond or oat milk' : 'chilled water') : 'chilled milk'), I('2 tbsp', c[2] === 'vegan' ? 'maple syrup or dates' : 'sugar'), I('1 cup', 'ice')],
      steps: [S('mix', 'Prepare the base (brew, soak or chop as needed).', 4), S('blend', 'Blend with the chilled milk/water, sweetener and ice until frothy.', 2), S('pour', 'Pour into tall glasses.', 1), S('garnish', 'Top with foam, a drizzle or a sprinkle. Serve chilled.', 1)], art: { kind: smoothie ? 'shake' : 'coffee', base: c[1] } });
  });

  // ------------------------------------------------------------------ ICE CREAMS
  var IC = [['Vanilla', '#f7eed2'], ['Chocolate', '#6b3a22'], ['Strawberry', '#f5a0b6'], ['Mango', '#f7b733'], ['Butterscotch', '#e6b35a'], ['Pista', '#b9d48a'], ['Kesar Pista', '#f3cf73'], ['Tutti Frutti', '#f6e6d6'], ['Coffee', '#a8784a'], ['Cookies & Cream', '#e0dcd4'], ['Mint Choco Chip', '#bfe8c8'], ['Black Currant', '#8a3a7a'], ['Blueberry', '#8a7ad0'], ['Caramel', '#d09a4a'], ['Salted Caramel', '#c98a3a'], ['Anjeer', '#b9786a'], ['Sitaphal', '#f3ece0'], ['Tender Coconut', '#f6f4e8'], ['Jackfruit', '#f3c64a'], ['Chikoo', '#c49a6a'], ['Rose', '#f5b0c6'], ['Gulkand', '#e07a9a'], ['Paan', '#9cc48a'], ['Banana', '#f3e08a'], ['Cheesecake', '#f6e6c0'], ['Peanut Butter', '#d0a060'], ['Choco Fudge', '#5a3322'], ['Rocky Road', '#6b4a3a'], ['Honey Almond', '#e9c887'], ['Green Tea', '#a8c88a'], ['Guava Chilli', '#f29a9a'], ['Litchi', '#f6e4e2'], ['Custard Apple', '#f1ebdf'], ['Coconut Jaggery', '#d9b27a'], ['Red Velvet', '#b3303a'], ['Brownie Fudge', '#5a3322'], ['Oreo Crunch', '#6a625a'], ['Dry Fruit', '#e2c48a']];
  each(IC, function (c) {
    add({ name: c[0] + ' Ice Cream', diet: 'veg', region: 'dessert', cats: ['icecream', 'dessert'], kcal: 260, flav: 'Sweet · Creamy', serves: 6, time: 25,
      ing: [I('2 cups', 'chilled whipping cream'), I('1 tin (400 g)', 'condensed milk'), I('', 'flavour: ' + c[0].toLowerCase() + ' (pulp, paste or chopped)'), I('1 tsp', 'vanilla essence')],
      steps: [S('whisk', 'Whip the chilled cream to stiff peaks.', 5), S('mix', 'Fold in the condensed milk, vanilla and the ' + c[0].toLowerCase() + ' flavour gently.', 3), S('pour', 'Pour into a freezer-safe box and smooth the top.', 1), S('freeze', 'Freeze 8 hours or overnight — no churning needed!', 8), S('serve', 'Scoop into bowls or cones and serve.', 1)], art: { kind: 'icecream', base: c[1] } });
  });
  each([['Malai Kulfi', '#f4ead0'], ['Kesar Kulfi', '#f3cf73'], ['Mango Kulfi', '#f7b733'], ['Pista Kulfi', '#b9d48a'], ['Rose Kulfi', '#f5b0c6'], ['Paan Kulfi', '#9cc48a'], ['Chocolate Kulfi', '#6b3a22'], ['Dry Fruit Kulfi', '#e2c48a'], ['Matka Kulfi', '#e9d3a0'], ['Falooda Kulfi', '#f5a6c0']], function (k) {
    add({ name: k[0], diet: 'veg', region: 'dessert', cats: ['icecream', 'dessert', 'north'], kcal: 240, flav: 'Rich · Milky', serves: 6, time: 40,
      ing: [I('1 litre', 'full-fat milk'), I('½ cup', 'sugar'), I('3 tbsp', 'milk powder'), I('', 'flavour: ' + k[0].replace(' Kulfi', '').toLowerCase()), I('2 tbsp', 'chopped pistachios & almonds')],
      steps: [S('boil', 'Boil the milk and reduce to half, stirring often so it doesn\'t catch.', 30), S('stir', 'Add sugar and milk powder; cook 5 minutes more.', 5), S('mix', 'Cool, then stir in the flavour and nuts.', 2), S('pour', 'Pour into kulfi moulds.', 2), S('freeze', 'Freeze 8 hours. Dip moulds in warm water to unmould.', 8)], art: { kind: 'kulfi', base: k[1] } });
  });
  each([['Mango Popsicle', '#f7b733'], ['Orange Ice Candy', '#f79a2a'], ['Kala Khatta Gola', '#5a2a5a'], ['Rose Milk Popsicle', '#f5b0c6'], ['Choco Bar', '#5a3322'], ['Watermelon Popsicle', '#f25a6a'], ['Coconut Popsicle', '#f6f4e8'], ['Strawberry Popsicle', '#f06a8a']], function (p) {
    var dairy = /Milk|Choco|Coconut/.test(p[0]);
    add({ name: p[0], diet: dairy ? 'veg' : 'vegan', region: 'dessert', cats: ['icecream', 'dessert'], kcal: 110, flav: 'Fruity · Icy', serves: 6, time: 15,
      ing: [I('2 cups', 'fruit juice / pulp / flavoured milk for ' + p[0].toLowerCase()), I('3 tbsp', 'sugar'), I('1 tbsp', 'lemon juice')], steps: [S('blend', 'Blend the fruit (or flavour) with sugar and lemon.', 3), S('pour', 'Pour into popsicle moulds and insert sticks.', 2), S('freeze', 'Freeze 6 hours until solid.', 6), S('serve', 'Run moulds under warm water to release. Enjoy!', 1)], art: { kind: 'popsicle', base: p[1] } });
  });
  each([['Hot Fudge Sundae', '#5a3322'], ['Banana Split', '#f3e08a'], ['Brownie Sundae', '#6b3a22'], ['Death by Chocolate', '#3a2018'], ['Royal Falooda', '#f5a6c0'], ['Gadbad Ice Cream', '#f29a6a'], ['Fruit Sundae', '#f5a05a'], ['Nutty Caramel Sundae', '#c98a3a']], function (s) {
    add({ name: s[0], diet: 'veg', region: 'dessert', cats: ['icecream', 'dessert'], kcal: 450, flav: 'Indulgent · Sweet', serves: 2, time: 10,
      ing: [I('4 scoops', 'ice cream (vanilla & chocolate)'), I('½ cup', 'chocolate sauce or fruit'), I('¼ cup', 'nuts & sprinkles'), I('2', 'cherries'), I('', 'whipped cream')], steps: [S('add', 'Layer sauce, ice cream and toppings in a tall glass.', 3), S('pour', 'Pour warm sauce over the top.', 1), S('garnish', 'Finish with whipped cream, nuts and a cherry.', 1)], art: { kind: 'sundae', base: s[1] } });
  });
  each([['Vegan Coconut Ice Cream', '#f6f4e8'], ['Vegan Mango Nice Cream', '#f7b733'], ['Vegan Chocolate Ice Cream', '#6b3a22'], ['Banana Nice Cream', '#f3e08a'], ['Lemon Sorbet', '#f4f0a0'], ['Mango Sorbet', '#f7b733'], ['Raspberry Sorbet', '#d0305a'], ['Watermelon Sorbet', '#f25a6a'], ['Guava Sorbet', '#f29a9a']], function (v) {
    add({ name: v[0], diet: 'vegan', region: 'dessert', cats: ['icecream', 'dessert'], kcal: 150, flav: /Sorbet/.test(v[0]) ? 'Fruity · Icy' : 'Creamy · Dairy-free', serves: 4, time: 15,
      ing: [I('3 cups', /Sorbet/.test(v[0]) ? 'fruit pulp' : 'frozen banana / coconut milk'), I('3 tbsp', 'maple syrup or sugar'), I('1 tbsp', 'lemon juice')], steps: [S('blend', 'Blend until completely smooth.', 3), S('pour', 'Pour into a container.', 1), S('freeze', 'Freeze 4–6 hours, stirring twice for a smoother texture.', 6), S('serve', 'Scoop and serve.', 1)], art: { kind: 'icecream', base: v[1] } });
  });

  // ------------------------------------------------------------------ CAKES & BAKES
  var CAKE = [['Vanilla', '#f6e6c0'], ['Chocolate', '#5a3322'], ['Red Velvet', '#b3303a'], ['Black Forest', '#3a2018'], ['White Forest', '#f6f0e6'], ['Pineapple', '#f3d45a'], ['Butterscotch', '#e0a64a'], ['Strawberry', '#f5a0b6'], ['Mango', '#f7b733'], ['Coffee', '#a8784a'], ['Lemon', '#f4ec8a'], ['Orange', '#f7a02a'], ['Carrot', '#ee8a2f'], ['Marble', '#c9a47a'], ['Chocolate Truffle', '#3a2018'], ['Rasmalai', '#f3dca0'], ['Gulab Jamun', '#b8602a'], ['Blueberry', '#6a5aa8'], ['Coconut', '#f6f4e8'], ['Pistachio', '#b9d48a'], ['Kitkat', '#8a5a3a'], ['Ferrero Rocher', '#8a5a2a'], ['Oreo', '#6a625a'], ['Rainbow', '#f28aa6'], ['Caramel', '#c98a3a']];
  each(CAKE, function (c) {
    [['', 'egg'], ['Eggless ', 'veg']].forEach(function (v) {
      add({ name: v[0] + c[0] + ' Cake', diet: v[1], region: 'dessert', cats: ['cakes', 'dessert'], kcal: 380, flav: 'Sweet · Soft', serves: 8, level: 'Medium', time: 70,
        ing: [I('1½ cups', 'maida (all-purpose flour)'), I('1 cup', 'sugar, powdered'), v[1] === 'egg' ? I('3', 'eggs') : I('1 cup', 'curd or condensed milk'), I('½ cup', 'oil or melted butter'), I('1 tsp', 'baking powder'), I('½ tsp', 'baking soda'), I('¾ cup', 'milk'), I('', 'flavour: ' + c[0].toLowerCase()), I('2 cups', 'whipped cream / frosting')],
        steps: [S('mix', 'Preheat the oven to 180°C and line a 7-inch tin.', 2), S('whisk', v[1] === 'egg' ? 'Beat the eggs and sugar until pale and fluffy, then add oil and milk.' : 'Whisk curd, sugar, oil and milk until smooth.', 5), S('mix', 'Sift in flour, baking powder and soda; fold gently with the ' + c[0].toLowerCase() + ' flavour. Don\'t overmix.', 3), S('pour', 'Pour into the tin and tap to remove air bubbles.', 1), S('bake', 'Bake 30–35 minutes until a toothpick comes out clean.', 35), S('rest', 'Cool completely on a rack.', 20), S('garnish', 'Layer and frost with whipped cream; decorate with ' + c[0].toLowerCase() + ' toppings.', 10)],
        art: { kind: 'cake', base: c[1] } });
    });
  });
  each([['Chocolate Mug Cake', '#5a3322'], ['Vanilla Mug Cake', '#f6e6c0'], ['Nutella Mug Cake', '#6b3a22'], ['Red Velvet Mug Cake', '#b3303a'], ['Coffee Mug Cake', '#a8784a']], function (m) {
    add({ name: m[0], diet: 'veg', region: 'dessert', cats: ['cakes', 'dessert', 'bachelor'], kcal: 350, flav: 'Warm · Gooey', serves: 1, time: 5,
      ing: [I('4 tbsp', 'maida'), I('3 tbsp', 'sugar'), I('3 tbsp', 'milk'), I('2 tbsp', 'oil'), I('¼ tsp', 'baking powder'), I('', 'flavour: ' + m[0].replace(' Mug Cake', '').toLowerCase())],
      steps: [S('mix', 'Whisk everything in a big microwave-safe mug until smooth.', 2), S('bake', 'Microwave 70–90 seconds until risen.', 2), S('serve', 'Rest 1 minute and eat warm — with ice cream if you like!', 1)], art: { kind: 'mugcake', base: m[1] } });
  });
  each([['Chocolate Cupcakes', '#5a3322'], ['Vanilla Cupcakes', '#f6e6c0'], ['Red Velvet Cupcakes', '#b3303a'], ['Blueberry Muffins', '#6a5aa8'], ['Choco Chip Muffins', '#c9a47a'], ['Banana Walnut Bread', '#c98a4a'], ['Fudgy Brownies', '#3a2018'], ['Eggless Brownies', '#4a2a1a'], ['Walnut Brownies', '#5a3322'], ['Blondies', '#e0b56a'], ['Plum Cake', '#6a2a1a'], ['Fruit Cake', '#a8602a'], ['New York Cheesecake', '#f6e6c0'], ['Blueberry Cheesecake', '#6a5aa8'], ['Mango Cheesecake (No-bake)', '#f7b733'], ['Tiramisu (Coffee, no alcohol)', '#c9a47a'], ['Choco Lava Cake', '#3a2018'], ['Swiss Roll', '#f28aa6'], ['Doughnuts', '#e9a85a'], ['Chocolate Chip Cookies', '#c9955a'], ['Nankhatai', '#f0d49a'], ['Coconut Cookies', '#f3e2b8'], ['Oatmeal Cookies', '#c9a06a'], ['Vegan Chocolate Cake', '#5a3322'], ['Vegan Banana Cake', '#e0b56a'], ['Vegan Carrot Cake', '#ee8a2f']], function (b) {
    var vegan = /Vegan/.test(b[0]), eggless = /Eggless|Nankhatai|No-bake|Tiramisu/.test(b[0]);
    add({ name: b[0], diet: vegan ? 'vegan' : eggless ? 'veg' : 'egg', region: 'dessert', cats: ['cakes', 'dessert'], kcal: 320, flav: 'Sweet · Baked', serves: 8, time: 50,
      ing: [I('1½ cups', 'flour'), I('¾ cup', 'sugar'), vegan ? I('½ cup', 'oil & plant milk') : eggless ? I('½ cup', 'curd / condensed milk') : I('2', 'eggs'), I('½ cup', vegan ? 'oil' : 'butter'), I('1 tsp', 'baking powder'), I('', 'flavour & add-ins for ' + b[0].toLowerCase())],
      steps: [S('mix', 'Preheat the oven to 180°C and prepare the tin / tray.', 2), S('whisk', 'Cream the fat and sugar (with eggs/curd) until light.', 4), S('mix', 'Fold in the dry ingredients and add-ins.', 3), S('bake', 'Bake until golden and set (time depends on size).', 25), S('rest', 'Cool before cutting or frosting.', 15), S('serve', 'Slice and serve.', 1)], art: { kind: /Cupcake|Muffin/.test(b[0]) ? 'cupcake' : /Cookie|Nankhatai|Doughnut/.test(b[0]) ? 'cookie' : /Brownie|Blondie/.test(b[0]) ? 'brownie' : 'cake', base: b[1] } });
  });

  // ------------------------------------------------------------------ Indian sweets & desserts
  var SWEET = [['Gulab Jamun', '#8a3a1a', 'fry'], ['Rasgulla', '#f7f3e8', 'boil'], ['Rasmalai', '#f3dca0', 'boil'], ['Rice Kheer', '#f4ead0', 'simmer'], ['Semiya Payasam', '#f1dcae', 'simmer'], ['Sabudana Kheer', '#f4ecd8', 'simmer'], ['Paal Payasam', '#f5e8cf', 'simmer'], ['Ada Pradhaman', '#b9824a', 'simmer'], ['Carrot Kheer', '#f2a55a', 'simmer'], ['Makhana Kheer', '#f1e6c8', 'simmer'], ['Gajar Halwa', '#e8702a', 'saute'], ['Moong Dal Halwa', '#d9a04a', 'saute'], ['Suji Halwa', '#e9c07a', 'saute'], ['Badam Halwa', '#e6b85a', 'saute'], ['Beetroot Halwa', '#a3264a', 'saute'], ['Lauki Halwa', '#c8d88a', 'saute'], ['Kesari Bath', '#f3a82f', 'saute'], ['Atta Halwa', '#b9723a', 'saute'], ['Besan Laddoo', '#e0a64a', 'mix'], ['Boondi Laddoo', '#f3a82f', 'fry'], ['Rava Laddoo', '#f1dcae', 'mix'], ['Coconut Laddoo', '#f6f0dc', 'mix'], ['Motichoor Laddoo', '#f79a2a', 'fry'], ['Dry Fruit Laddoo', '#a8704a', 'mix'], ['Til Laddoo', '#c9a06a', 'mix'], ['Kaju Katli', '#f1e6d0', 'mix'], ['Coconut Barfi', '#f6f0dc', 'mix'], ['Milk Barfi', '#f3e8cc', 'mix'], ['Besan Barfi', '#e0a64a', 'mix'], ['Jalebi', '#f3a82f', 'fry'], ['Mysore Pak', '#e8b43a', 'mix'], ['Double Ka Meetha', '#d9803a', 'fry'], ['Qubani Ka Meetha', '#c9702a', 'simmer'], ['Shrikhand', '#f6e8c8', 'mix'], ['Basundi', '#f3dca0', 'simmer'], ['Rabri', '#f4e6c8', 'simmer'], ['Phirni', '#f4ecd8', 'simmer'], ['Caramel Custard', '#e0a64a', 'steam'], ['Chocolate Mousse', '#5a3322', 'mix'], ['Fruit Custard', '#f4d86a', 'simmer'], ['Sheer Khurma', '#efdcae', 'simmer'], ['Modak', '#f6f0dc', 'steam'], ['Puran Poli', '#e0a64a', 'roll'], ['Obbattu', '#e6ad4a', 'roll'], ['Kozhukattai', '#f6f0dc', 'steam'], ['Unniyappam', '#8a4a1a', 'fry'], ['Kalakand', '#f3e8cc', 'simmer'], ['Peda', '#e9d3a0', 'mix'], ['Sandesh', '#f6efdc', 'mix'], ['Malpua', '#d9903a', 'fry'], ['Ghevar', '#f0c05a', 'fry'], ['Soan Papdi', '#f2dea0', 'mix'], ['Chikki', '#b9823a', 'mix'], ['Coconut Burfi (Vegan)', '#f6f0dc', 'mix'], ['Chocolate Barfi', '#6b3a22', 'mix'], ['Mango Phirni', '#f7b733', 'simmer'], ['Ragi Halwa', '#8a5a3c', 'saute'], ['Pineapple Kesari', '#f3c64a', 'saute'], ['Bread Halwa', '#c9803a', 'saute'], ['Palkova', '#e2b87a', 'simmer']];
  each(SWEET, function (s) {
    var vegan = /Vegan|Chikki/.test(s[0]);
    add({ name: s[0], diet: /Custard|Mousse/.test(s[0]) && /Caramel|Mousse/.test(s[0]) ? 'egg' : vegan ? 'vegan' : 'veg', region: 'dessert', cats: ['sweets', 'dessert', /Payasam|Pradhaman|Mysore|Kesari|Obbattu|Kozhukattai|Unniyappam|Palkova|Ragi|Pineapple|Double|Qubani/.test(s[0]) ? 'south' : 'north'], kcal: 330, flav: 'Sweet · Festive', serves: 6,
      ing: [I('', 'main: ' + s[0].toLowerCase().replace(/ \(.*\)/, '')), I('¾ cup', /Laddoo|Halwa|Barfi|Kesari|Mysore/.test(s[0]) ? 'sugar' : 'sugar or jaggery'), I('3 tbsp', vegan ? 'coconut oil' : 'ghee'), I('½ tsp', 'cardamom powder'), I('2 tbsp', 'cashews, almonds & raisins'), I('pinch', 'saffron')],
      steps: [S('mix', 'Measure and prepare all the ingredients for ' + s[0] + '.', 5), S(s[2], s[2] === 'simmer' ? 'Cook slowly in milk, stirring often, until thick and creamy.' : s[2] === 'fry' ? 'Shape and fry on low-medium heat until evenly golden.' : s[2] === 'boil' ? 'Cook in simmering sugar syrup until spongy and doubled in size.' : s[2] === 'steam' ? 'Fill or pour into moulds and steam until set.' : s[2] === 'roll' ? 'Stuff sweet filling into dough, roll gently and roast on a tawa with ghee.' : 'Cook in ghee on low heat, stirring constantly, until it leaves the sides of the pan.', 20),
        S('add', 'Add sugar/syrup, cardamom and saffron and mix well.', 3), S('garnish', 'Garnish with fried nuts. Serve warm or chilled.', 2)],
      art: { kind: /Kheer|Payasam|Pradhaman|Phirni|Basundi|Rabri|Khurma|Custard|Mousse|Shrikhand/.test(s[0]) ? 'kheer' : /Halwa|Kesari/.test(s[0]) ? 'halwa' : /Jamun|Rasgulla|Rasmalai|Laddoo|Modak|Kozhukattai|Unniyappam|Peda/.test(s[0]) ? 'laddoo' : /Jalebi/.test(s[0]) ? 'jalebi' : 'barfi', base: s[1] } });
  });

  // ------------------------------------------------------------------ bachelor specials (quick, minimal)
  each([['One-Pot Dal Rice', 'vegan', 'Rice, dal and veggies in one cooker'], ['Bread Upma', 'vegan', 'Leftover bread tossed with onion and tempering'], ['Masala Oats', 'vegan', 'Savoury oats with veggies'], ['Poha', 'vegan', 'Flattened rice with peanuts and lemon'], ['Leftover Rice Fried Rice', 'vegan', 'Yesterday\'s rice, today\'s dinner'], ['Chilli Cheese Toast', 'veg', 'Cheese, chilli and bread under a lid'], ['Paneer Bhurji Roll', 'veg', 'Paneer bhurji wrapped in a roti'], ['Aloo Fry', 'vegan', 'Crispy spiced potatoes in 15 minutes'], ['Instant Tomato Rice', 'vegan', 'Tomato masala mixed with rice'], ['Microwave Khichdi', 'veg', 'Rice and dal in the microwave'], ['Egg Curry in 20 Minutes', 'egg', 'Quick onion-tomato egg curry'], ['Quick Chicken Fry', 'nonveg', 'Boneless chicken, spices, done'], ['Peanut Chutney Rice', 'vegan', 'Rice mixed with peanut podi'], ['Instant Rava Dosa', 'vegan', 'No-ferment crispy dosa'], ['Chana Chaat', 'vegan', 'Canned chickpeas + onion + lemon'], ['Curd Rice (Quick)', 'veg', 'Leftover rice made heavenly'], ['Tawa Pulao', 'vegan', 'Mumbai-style pulao with pav bhaji masala'], ['Sabudana Khichdi', 'vegan', 'Soaked sago with peanuts'], ['Besan Chilla', 'vegan', 'Savoury gram-flour pancakes'], ['Moong Dal Chilla', 'vegan', 'Protein-rich lentil pancakes'], ['Sweet Potato Chaat', 'vegan', 'Roasted sweet potato with chaat masala'], ['Banana Pancakes', 'egg', '2-ingredient banana + egg pancakes'], ['Peanut Butter Oats', 'vegan', 'Overnight oats with PB and banana'], ['Maggi Omelette', 'egg', 'Maggi + eggs = genius']], function (b) {
    add({ name: b[0], diet: b[1], region: 'bachelor', cats: ['bachelor', 'fast', b[1] === 'egg' ? 'eggs' : ''], kcal: 330, flav: 'Quick · Tasty', serves: 1, time: 15,
      ing: [I('', 'main: ' + b[0].toLowerCase().replace(/ \(.*\)| in 20 minutes/i, '')), I('1', 'onion'), I('1', 'green chilli'), I('1 tbsp', b[1] === 'veg' ? 'butter' : 'oil'), I('', 'salt & basic spices')],
      steps: [S('chop', 'Chop the onion and chilli — that\'s all the prep.', 2), S('saute', 'Sauté them in oil for 2 minutes.', 2), S('add', b[2] + '.', 6), S('serve', 'Eat straight from the pan — fewer dishes to wash!', 1)], art: { kind: 'bowl', base: '#e5b25a' } });
  });
})(typeof window !== 'undefined' ? window : globalThis);
